[package]
name = "mps-test"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "move"
path = "src/move.rs"

[[bin]]
name = "vs"
path = "src/vs.rs"

[[bin]]
name = "sc"
path = "src/sc.rs"

[[bin]]
name = "sparse"
path = "src/sparse.rs"

[dependencies]
anyhow = "1.0.79"
tch = "0.13.0"
