[package]
name = "mps-torch"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "move"
path = "src/move.rs"

[[bin]]
name = "vs"
path = "src/vs.rs"

[[bin]]
name = "fc"
path = "src/fc.rs"

[[bin]]
name = "sparse_f16"
path = "src/sparse_f16.rs"

[dependencies]
anyhow = "1.0.79"
tch = "0.15.0"
